services:
  - type: web
    name: salestracker
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn salestracker.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DATABASE_URL
        value: postgresql://postgres.mehipkdatrttvghmfgmo:jmvv2004%2F05.@aws-0-us-west-2.pooler.supabase.com:6543/postgres
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
