# Generated by Django 6.0.7 on 2026-08-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('internet', 'internet'), ('tv', 'tv'), ('combo', 'combo')], max_length=10)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('ventas', 'ventas')], default='ventas', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clientCode', models.CharField(max_length=40)),
                ('clientName', models.CharField(max_length=160)),
                ('serviceType', models.CharField(choices=[('internet', 'internet'), ('tv', 'tv'), ('combo', 'combo')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lastEditedAt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.plan')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to='core.user')),
                ('lastEditedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_edited', to='core.user')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('personName', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concept', models.CharField(blank=True, default='', max_length=255)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('coin_050', models.PositiveIntegerField(default=0)),
                ('coin_1', models.PositiveIntegerField(default=0)),
                ('coin_2', models.PositiveIntegerField(default=0)),
                ('coin_5', models.PositiveIntegerField(default=0)),
                ('bill_10', models.PositiveIntegerField(default=0)),
                ('bill_20', models.PositiveIntegerField(default=0)),
                ('bill_50', models.PositiveIntegerField(default=0)),
                ('bill_100', models.PositiveIntegerField(default=0)),
                ('bill_200', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
    ]
