# Generated by Django 6.0.7 on 2026-08-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='changeReason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='planFrom',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='sale',
            name='requestType',
            field=models.CharField(choices=[('nuevo_contrato', 'NUEVO CONTRATO'), ('cambio_plan', 'CAMBIO DE PLAN'), ('recontratacion', 'RECONTRATACION'), ('retiro', 'RETIRO'), ('adicion', 'ADICIÓN'), ('baja_temporal', 'BAJA TEMPORAL'), ('otro', 'OTRO')], default='nuevo_contrato', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='totalFrom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer'),
        ),
    ]
