# Generated by Django 6.0.7 on 2026-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_sale_changereason_sale_notes_sale_planfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Plan del catalogo anterior; solo se ofrece en retiros.'),
        ),
    ]
