# Generated by Django 6.0.7 on 2026-08-12 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
