# Generated by Django 6.0.7 on 2026-08-18 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outflow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashcount',
            unique_together={('date', 'createdBy')},
        ),
    ]
