# Generated by Django 6.0.7 on 2026-08-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cashcount_date_alter_outflow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='requestType',
            field=models.CharField(choices=[('nuevo_contrato', 'NUEVO CONTRATO'), ('cambio_plan', 'CAMBIO DE PLAN'), ('recontratacion', 'RECONTRATACION'), ('retiro', 'RETIRO'), ('adicion', 'ADICION'), ('baja_temporal', 'BAJA TEMPORAL'), ('otro', 'OTRO')], default='nuevo_contrato', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='serviceType',
            field=models.CharField(choices=[('internet', 'INTERNET'), ('tv', 'TV ANALOGA'), ('tv_digital', 'TV DIGITAL'), ('combo_analog', 'INTERNET + TV ANALOGA'), ('combo_digital', 'INTERNET + TV DIGITAL')], max_length=20),
        ),
    ]
