# Generated by Django 6.0.7 on 2026-08-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sale_requesttype_alter_sale_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('automatic', 'Automatico'), ('manual', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Correcto'), ('failed', 'Fallido')], default='success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
