# Generated by Django 6.0.7 on 2026-08-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_backup_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
