# Generated by Django 6.0.7 on 2026-09-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_email_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcount',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
