# Generated by Django 6.0.7 on 2026-09-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cashcount_saldo_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='CashCount',
        ),
        migrations.DeleteModel(
            name='Outflow',
        ),
    ]
