# Generated by Django 6.0.7 on 2026-09-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_outflow_createdby_delete_cashcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='applied_installation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de instalacion aplicado', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='applied_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mensualidad aplicada', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='promotion_name',
            field=models.CharField(blank=True, default='', help_text='Nombre de la promocion al momento del registro', max_length=120),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('apply_installation', models.BooleanField(default=False, help_text='Si aplica precio promocional a instalacion')),
                ('apply_monthly', models.BooleanField(default=False, help_text='Si aplica precio promocional a mensualidad')),
                ('installation_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional de instalacion (solo si apply_installation)', max_digits=12, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional de mensualidad (solo si apply_monthly)', max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to='core.user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.plan')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Promocion utilizada (snapshot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.promotion'),
        ),
    ]
