# Generated by Django 6.0.7 on 2026-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sale_applied_installation_sale_applied_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='additionType',
            field=models.CharField(blank=True, choices=[('adicion_internet', 'ADICION INTERNET'), ('adicion_tv', 'ADICION TV')], default='', help_text='Sub-tipo de adicion: internet o tv', max_length=20),
        ),
    ]
