# Generated by Django 6.0.7 on 2026-09-25 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_addition_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='planFromId',
            field=models.ForeignKey(blank=True, help_text='Plan anterior (cambio de plan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_from', to='core.plan'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='requestType',
            field=models.CharField(choices=[('nuevo_contrato', 'NUEVO CONTRATO'), ('cambio_plan', 'CAMBIO DE PLAN'), ('recontratacion', 'RECONTRATACION'), ('retiro', 'RETIRO'), ('adicion', 'ADICION'), ('otro', 'OTRO')], default='nuevo_contrato', max_length=20),
        ),
    ]
