# Generated by Django 6.0.7 on 2026-09-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_planFromId'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backup_format',
            field=models.CharField(choices=[('dump', 'PostgreSQL dump (pg_dump)'), ('sqlite3', 'SQLite')], default='dump', max_length=10),
        ),
        migrations.AddField(
            model_name='backup',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='backup',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='verified',
            field=models.BooleanField(default=False, help_text='La integridad del archivo fue verificada tras generarse'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En proceso'), ('success', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
