# Generated by Django 6.0.7 on 2026-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_backup_manual_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_format',
            field=models.CharField(choices=[('dump', 'PostgreSQL dump (pg_dump)'), ('sqlite3', 'SQLite'), ('json', 'JSON (solo desarrollo)')], default='dump', max_length=10),
        ),
    ]
