# Generated by Django 6.0.7 on 2026-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backup_format_json'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='backup',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='backup_unico_en_proceso'),
        ),
    ]
