# Generated by Django 6.0.7 on 2026-09-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_backup_unico_en_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='serviceTypeFrom',
            field=models.CharField(blank=True, choices=[('internet', 'INTERNET'), ('tv', 'TV ANALOGA'), ('tv_digital', 'TV DIGITAL'), ('combo_analog', 'INTERNET + TV ANALOGA'), ('combo_digital', 'INTERNET + TV DIGITAL')], help_text='Servicio anterior (cambio de plan entre servicios)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='planFromId',
            field=models.ForeignKey(blank=True, help_text='Plan anterior (cambio de plan)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_from', to='core.plan'),
        ),
    ]
