# Generated by Django 6.0.7 on 2026-10-01 17:01

from django.db import migrations, models


# Los tipos que el sistema tenia antes, cada uno con el modo que
# reproducia su comportamiento anterior. El code no cambia: es lo que ya
# esta guardado en core_sale.requestType. Si se sembrara uno con un code
# distinto, el historial quedaria sin tipo.
TIPOS_INICIALES = [
    ('nuevo_contrato', 'NUEVO CONTRATO', 'nuevo', 10),
    ('cambio_plan', 'CAMBIO DE PLAN', 'cambio_plan', 20),
    ('recontratacion', 'RECONTRATACION', 'nuevo', 30),
    ('retiro', 'RETIRO', 'retiro', 40),
    ('adicion', 'ADICION', 'adicion', 50),
    ('otro', 'OTRO', 'simple', 60),
]


def sembrar_tipos(apps, schema_editor):
    TipoSolicitud = apps.get_model('core', 'TipoSolicitud')
    for code, nombre, modo, orden in TIPOS_INICIALES:
        TipoSolicitud.objects.update_or_create(
            code=code,
            defaults={'nombre': nombre, 'modo': modo, 'orden': orden,
                      'activo': True},
        )


def quitar_tipos(apps, schema_editor):
    apps.get_model('core', 'TipoSolicitud').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cambio_plan_entre_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('modo', models.CharField(choices=[('nuevo', 'Nuevo contrato'), ('retiro', 'Retiro'), ('cambio_plan', 'Cambio de plan'), ('adicion', 'Adicion'), ('simple', 'Sin reglas especiales')], default='simple', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='requestType',
            field=models.CharField(blank=True, default='nuevo_contrato', help_text='Codigo de TipoSolicitud; el catalogo vive en esa tabla', max_length=20),
        ),
        migrations.RunPython(sembrar_tipos, quitar_tipos),
    ]
