# Generated by Django 6.0.7 on 2026-10-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tipos_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('cambio', 'Motivo del cambio'), ('retiro', 'Motivo del retiro')], max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='changeReason',
            field=models.CharField(blank=True, default='', help_text='Snapshot del nombre del motivo al momento del registro', max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='motivo',
            field=models.ForeignKey(blank=True, help_text='Motivo del cambio o del retiro, segun la categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.motivo'),
        ),
    ]
